version: '3'
services:
  znode1:
    image: confluentinc/cp-zookeeper:latest
    hostname: znode1
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_SERVERS: znode1:12888:13888;znode2:22888:23888;znode3:32888:33888
  znode2:
    image: confluentinc/cp-zookeeper:latest
    hostname: znode2
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_SERVERS: znode1:12888:13888;znode2:22888:23888;znode3:32888:33888
  znode3:
    image: confluentinc/cp-zookeeper:latest
    hostname: znode3
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_SERVERS: znode1:12888:13888;znode2:22888:23888;znode3:32888:33888
  knode1:
    image: confluentinc/cp-kafka:latest
    hostname: knode1
    ports:
      - "19092:19092"
    depends_on:
      - znode1
      - znode2
      - znode3
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: znode1:12181,znode2:12181,znode3:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://knode1:19092
  knode2:
    image: confluentinc/cp-kafka:latest
    hostname: knode2
    ports:
      - "29092:29092"
    depends_on:
      - znode1
      - znode2
      - znode3
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: znode1:12181,znode2:12181,znode3:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://knode2:29092
  knode3:
    image: confluentinc/cp-kafka:latest
    hostname: knode3
    ports:
      - "39092:39092"
    depends_on:
      - znode1
      - znode2
      - znode3
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: znode1:12181,znode2:12181,znode3:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://knode3:39092
